/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TokenBalancesRequest {
    /**
     * Set to `true` to return ERC721 and ERC1155 assets. Defaults to `false`.
     */
    nft?: boolean;
    /**
     * Set to `true` to skip fetching NFT metadata, which can result in faster responses.  Defaults to `false` and only applies when `nft=true`.
     *
     */
    noNftFetch?: boolean;
    /**
     * The requested fiat currency.
     */
    quoteCurrency?: string;
}
