/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovalentApi } from "@fern-api/covalent";

export interface BalanceResponseType {
    /** The requested wallet address. */
    address: string;
    /** The updated time in UTC. */
    updatedAt: Date;
    /** The next updated time in UTC. */
    nextUpdateAt: Date;
    /** The requested fiat currency. */
    quoteCurrency: string;
    items: CovalentApi.classA.WalletBalanceItem[];
}
