/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovalentApi } from "@fern-api/covalent";

export interface HistoricalPortfolioResponse {
    /** The requested wallet address. */
    address: string;
    /** The updated time in UTC. */
    updatedAt: Date;
    /** The next updated time in UTC. */
    nextUpdateAt: Date;
    /** The requested fiat currency. */
    quoteCurrency: string;
    /** The requested chain ID. */
    chainId: number;
    /** List of tokens in portfolio */
    items: unknown[];
    pagination: CovalentApi.AppliedPagination;
}
