/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CovalentApi } from "@fern-api/covalent";

export interface Holding {
    /** Timestamp for holding. */
    timestamp: Date;
    /** Quote rate for holding. */
    quoteRate: number;
    open: CovalentApi.classA.Balance;
    high: CovalentApi.classA.Balance;
    low: CovalentApi.classA.Balance;
    close: CovalentApi.classA.Balance;
}
