/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         contractDecimals: 18,
 *         contractName: "Frontier Token",
 *         contractTickerSymbol: "FRONT",
 *         contractAddress: "0xf8c3527cc04340b208c854e985240c02f7b7793f",
 *         supportsErc: ["erc20"],
 *         logoUrl: "https://logos.covalenthq.com/tokens/1/0xf8c3527cc04340b208c854e985240c02f7b7793f.png",
 *         lastTransferredAt: new Date("2022-09-27T15:29:11Z"),
 *         nativeToken: false,
 *         type: "cryptocurrency",
 *         balance: "4843997835959514312853",
 *         balance24H: "4843997835959514312853",
 *         quoteRate: 0.212,
 *         quoteRate24H: 0.21129668,
 *         quote: 1026.9275,
 *         quote24H: 1023.5206
 *     }
 */
export interface WalletBalanceItem {
    /** Smart contract decimals. */
    contractDecimals: number;
    /** Smart contract name. */
    contractName: string;
    /** Smart contract ticker symbol. */
    contractTickerSymbol: string;
    /** Smart contract address. */
    contractAddress: string;
    /**
     * The standard interface(s) supported for this token, eg: `ERC-20`.
     *
     */
    supportsErc: string[];
    /** Smart contract URL. */
    logoUrl: string;
    /** Last transferred date for a wallet. */
    lastTransferredAt: Date;
    /**
     * Indicates if a token is the chain's native gas token, eg: ETH on Ethereum.
     *
     */
    nativeToken: boolean;
    /** One of `cryptocurrency`, `stablecoin`, `nft` or `dust`. */
    type: string;
    /** The asset balance. Use `contract_decimals` to scale this balance for display purposes. */
    balance: string;
    /** The asset balance 24 hours ago. */
    balance24H: string;
    /** The current spot exchange rate in `quote-currency`. */
    quoteRate: number;
    /** The spot exchange rate in `quote-currency` as of 24 hours ago. */
    quoteRate24H: number;
    /** The current balance converted to fiat in `quote-currency`. */
    quote: number;
    quote24H: number;
}
