/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WalletBalanceItem {
    /** Smart contract decimals. */
    contractDecimals: number;
    /** Smart contract name. */
    contractName: string;
    /** Smart contract ticker symbol. */
    contractTickerSymbol: string;
    /** Smart contract address. */
    contractAddress: string;
    /**
     * The standard interface(s) supported for this token, eg: `ERC-20`.
     *
     */
    supportsErc: string[];
    /** Smart contract URL. */
    logoUrl: string;
    /** Last transferred date for a wallet. */
    lastTransferredAt: Date;
    /**
     * Indicates if a token is the chain's native gas token, eg: ETH on Ethereum.
     *
     */
    nativeToken: boolean;
    /** One of `cryptocurrency`, `stablecoin`, `nft` or `dust`. */
    type: string;
    /** The asset balance. Use `contract_decimals` to scale this balance for display purposes. */
    balance: number;
    /** The asset balance 24 hours ago. */
    balance24H: number;
    /** The current spot exchange rate in `quote-currency`. */
    quoteRate: number;
    /** The spot exchange rate in `quote-currency` as of 24 hours ago. */
    quoteRate24H: number;
    /** The current balance converted to fiat in `quote-currency`. */
    quote: number;
    quote24H: number;
}
