/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TokenIdResponse {
    /** Smart contract decimals. */
    contractDecimals: number;
    /** Smart contract name. */
    contractName: string;
    /** Smart contract ticker symbol. */
    contractTickerSymbol: string;
    /** Smart contract address. */
    contractAddress: string;
    /**
     * The standard interface(s) supported for this token, eg: `ERC-20`.
     *
     */
    supportsErc: string[];
    /** Smart contract URL. */
    logoUrl: string;
    /** The list of token ids under the contract address. */
    tokenId: number;
}
