/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CovalentApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CovalentApiTimeoutError.prototype);
    }
}
