/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.classA.nft.getTokenIds.Response.Raw,
    CovalentApi.classA.TokenIdResponseType
> = core.serialization.lazyObject(async () => (await import("../../../../..")).classA.TokenIdResponseType);

export declare namespace Response {
    type Raw = serializers.classA.TokenIdResponseType.Raw;
}
