/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         contractDecimals: 0,
 *         contractName: "Meme Ltd.",
 *         contractTickerSymbol: "MEMES",
 *         contractAddress: "0xe4605d46fd0b3f8329d936a8b258d69276cba264",
 *         supportsErc: undefined,
 *         logoUrl: "https://logos.covalenthq.com/tokens/0xe4605d46fd0b3f8329d936a8b258d69276cba264.png",
 *         tokenId: "1"
 *     }
 */
export interface TokenIdResponse {
    /** Smart contract decimals. */
    contractDecimals: number;
    /** Smart contract name. */
    contractName: string;
    /** Smart contract ticker symbol. */
    contractTickerSymbol: string;
    /** Smart contract address. */
    contractAddress: string;
    /**
     * The standard interface(s) supported for this token, eg: `ERC-20`.
     *
     */
    supportsErc?: string[];
    /** Smart contract URL. */
    logoUrl: string;
    /** The list of token ids under the contract address. */
    tokenId: string;
}
