/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TokenIdsRequestType {
    /**
     * The specific page to be returned.
     */
    pageNumber?: number;
    /**
     * The number of results per page.
     */
    pageSize?: number;
}
