/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Client as BalancesClient } from "../resources/balances/client/Client";
import { Client as NftClient } from "../resources/nft/client/Client";

export declare namespace Client {
    interface Options {
        environment?: environments.CovalentApiEnvironment | string;
        credentials?: core.Supplier<core.BasicAuth>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    #balances: BalancesClient | undefined;

    public get balances(): BalancesClient {
        return (this.#balances ??= new BalancesClient(this.options));
    }

    #nft: NftClient | undefined;

    public get nft(): NftClient {
        return (this.#nft ??= new NftClient(this.options));
    }
}
