/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../../../core";

export const TokenIdResponseType: core.serialization.ObjectSchema<
    serializers.classA.TokenIdResponseType.Raw,
    CovalentApi.classA.TokenIdResponseType
> = core.serialization.object({
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    items: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../../..")).classA.TokenIdResponse)
    ),
    pagination: core.serialization
        .lazyObject(async () => (await import("../../../../..")).AppliedPagination)
        .optional(),
});

export declare namespace TokenIdResponseType {
    interface Raw {
        updated_at: string;
        items: serializers.classA.TokenIdResponse.Raw[];
        pagination?: serializers.AppliedPagination.Raw | null;
    }
}
