/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AppliedPagination {
    /** true if we can paginate to get more data. */
    hasMore?: boolean;
    /** The specific page being returned. */
    pageNumber?: number;
    /** The number of results per page. */
    pageSize?: number;
    /** Total number of entries. */
    totalCount?: number;
}
