/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as ClassAClient } from "./api/resources/classA/client/Client";
import { Client as PricingClient } from "./api/resources/pricing/client/Client";

export declare namespace CovalentApiClient {
    interface Options {
        environment?: environments.CovalentApiEnvironment | string;
        credentials?: core.Supplier<core.BasicAuth>;
    }
}

export class CovalentApiClient {
    constructor(private readonly options: CovalentApiClient.Options) {}

    #classA: ClassAClient | undefined;

    public get classA(): ClassAClient {
        return (this.#classA ??= new ClassAClient(this.options));
    }

    #pricing: PricingClient | undefined;

    public get pricing(): PricingClient {
        return (this.#pricing ??= new PricingClient(this.options));
    }
}
