/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CovalentApiEnvironment = {
    Production: "https://api.covalenthq.com",
} as const;

export type CovalentApiEnvironment = typeof CovalentApiEnvironment.Production;
