/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../../../core";

export const BalanceResponseType: core.serialization.ObjectSchema<
    serializers.classA.BalanceResponseType.Raw,
    CovalentApi.classA.BalanceResponseType
> = core.serialization.object({
    address: core.serialization.string(),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
    nextUpdateAt: core.serialization.property("next_update_at", core.serialization.date()),
    quoteCurrency: core.serialization.property("quote_currency", core.serialization.string()),
    items: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../../..")).classA.WalletBalanceItem)
    ),
});

export declare namespace BalanceResponseType {
    interface Raw {
        address: string;
        updated_at: string;
        next_update_at: string;
        quote_currency: string;
        items: serializers.classA.WalletBalanceItem.Raw[];
    }
}
