/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../../../core";

export const Balance: core.serialization.ObjectSchema<serializers.classA.Balance.Raw, CovalentApi.classA.Balance> =
    core.serialization.object({
        balance: core.serialization.string(),
        quote: core.serialization.number(),
    });

export declare namespace Balance {
    interface Raw {
        balance: string;
        quote: number;
    }
}
