/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../../../core";

export const InftMetadata: core.serialization.Schema<
    serializers.classA.InftMetadata.Raw,
    CovalentApi.classA.InftMetadata
> = core.serialization.list(core.serialization.unknown());

export declare namespace InftMetadata {
    type Raw = unknown[];
}
