/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../../../core";

export const WalletBalanceItem: core.serialization.ObjectSchema<
    serializers.classA.WalletBalanceItem.Raw,
    CovalentApi.classA.WalletBalanceItem
> = core.serialization.object({
    contractDecimals: core.serialization.property("contract_decimals", core.serialization.number()),
    contractName: core.serialization.property("contract_name", core.serialization.string()),
    contractTickerSymbol: core.serialization.property("contract_ticker_symbol", core.serialization.string()),
    contractAddress: core.serialization.property("contract_address", core.serialization.string()),
    supportsErc: core.serialization.property("supports_erc", core.serialization.list(core.serialization.string())),
    logoUrl: core.serialization.property("logo_url", core.serialization.string()),
    lastTransferredAt: core.serialization.property("last_transferred_at", core.serialization.date()),
    nativeToken: core.serialization.property("native_token", core.serialization.boolean()),
    type: core.serialization.string(),
    balance: core.serialization.string(),
    balance24H: core.serialization.property("balance_24h", core.serialization.string()),
    quoteRate: core.serialization.property("quote_rate", core.serialization.number()),
    quoteRate24H: core.serialization.property("quote_rate_24h", core.serialization.number()),
    quote: core.serialization.number(),
    quote24H: core.serialization.property("quote_24h", core.serialization.number()),
});

export declare namespace WalletBalanceItem {
    interface Raw {
        contract_decimals: number;
        contract_name: string;
        contract_ticker_symbol: string;
        contract_address: string;
        supports_erc: string[];
        logo_url: string;
        last_transferred_at: string;
        native_token: boolean;
        type: string;
        balance: string;
        balance_24h: string;
        quote_rate: number;
        quote_rate_24h: number;
        quote: number;
        quote_24h: number;
    }
}
