/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CovalentApi } from "@fern-api/covalent";
import * as core from "../../../../core";

export const AppliedPagination: core.serialization.ObjectSchema<
    serializers.AppliedPagination.Raw,
    CovalentApi.AppliedPagination
> = core.serialization.object({
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    pageNumber: core.serialization.property("page_number", core.serialization.number()),
    pageSize: core.serialization.property("page_size", core.serialization.number()),
    totalCount: core.serialization.property("total_count", core.serialization.number()),
});

export declare namespace AppliedPagination {
    interface Raw {
        has_more: boolean;
        page_number: number;
        page_size: number;
        total_count: number;
    }
}
